// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQJw91D_i-zA4obm3GfzjRpaDoVetG5OA',
    appId: '1:481214437178:android:d4834f48b145e156412203',
    messagingSenderId: '481214437178',
    projectId: 'zoom-3c767',
    databaseURL: 'https://zoom-3c767-default-rtdb.firebaseio.com',
    storageBucket: 'zoom-3c767.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDET3kC7HQioMga3nHev52GC5g-i0ckUg4',
    appId: '1:481214437178:ios:0d2b497e3adf975d412203',
    messagingSenderId: '481214437178',
    projectId: 'zoom-3c767',
    databaseURL: 'https://zoom-3c767-default-rtdb.firebaseio.com',
    storageBucket: 'zoom-3c767.appspot.com',
    iosClientId: '481214437178-s9jcdnjmnn8mp2mo6o2irt542llvoira.apps.googleusercontent.com',
    iosBundleId: 'health.mymeds.app.mymedsApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWDbl_4bUZG2IHDxnxPcan-eBzZtsuY0M',
    appId: '1:481214437178:web:eb621d71c88af5d4412203',
    messagingSenderId: '481214437178',
    projectId: 'zoom-3c767',
    authDomain: 'zoom-3c767.firebaseapp.com',
    databaseURL: 'https://zoom-3c767-default-rtdb.firebaseio.com',
    storageBucket: 'zoom-3c767.appspot.com',
    measurementId: 'G-W25S1BEK4D',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDET3kC7HQioMga3nHev52GC5g-i0ckUg4',
    appId: '1:481214437178:ios:579c40ede36882d6412203',
    messagingSenderId: '481214437178',
    projectId: 'zoom-3c767',
    databaseURL: 'https://zoom-3c767-default-rtdb.firebaseio.com',
    storageBucket: 'zoom-3c767.appspot.com',
    iosClientId: '481214437178-inm7fmbvk8lluq8l3m2me2dcqb6o0fkb.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDo8Qb_svD9e3lQUo1FL_MabzLrcDabdc8',
    appId: '1:481214437178:web:deca79823a501ce1412203',
    messagingSenderId: '481214437178',
    projectId: 'zoom-3c767',
    authDomain: 'zoom-3c767.firebaseapp.com',
    databaseURL: 'https://zoom-3c767-default-rtdb.firebaseio.com',
    storageBucket: 'zoom-3c767.appspot.com',
    measurementId: 'G-46GWLHDJP3',
  );

}