import 'dart:async';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';

/// Service de détection des médicaments oubliés
/// Vérifie périodiquement si des médicaments n'ont pas été pris
/// dans les 30 minutes suivant l'heure prévue
class MissedMedicationService {
  static final MissedMedicationService _instance = MissedMedicationService._();
  factory MissedMedicationService() => _instance;
  MissedMedicationService._();

  final FirebaseFirestore _firestore = FirebaseFirestore.instance;
  Timer? _checkTimer;
  bool _isRunning = false;
  String? _userEmail;

  void start(String userEmail) {
    if (_isRunning) return;
    _isRunning = true;
    _userEmail = userEmail;
    _checkMissedMeds();
    // Vérifier toutes les 60 secondes
    _checkTimer = Timer.periodic(const Duration(seconds: 60), (_) {
      _checkMissedMeds();
    });
    print('✅ MissedMedicationService started for $userEmail');
  }

  void stop() {
    _checkTimer?.cancel();
    _checkTimer = null;
    _isRunning = false;
  }

  Future<void> _checkMissedMeds() async {
    if (_userEmail == null) return;

    try {
      final now = DateTime.now();
      final gracePeriod = now.subtract(const Duration(minutes: 30));
      final cutoffTime = now.subtract(const Duration(minutes: 5));

      // Récupérer les médicaments de l'utilisateur
      final medsSnapshot = await _firestore
          .collection('Users')
          .doc(_userEmail)
          .collection('Medications')
          .get();

      for (final medDoc in medsSnapshot.docs) {
        // Récupérer les logs pour les heures entre cutoffTime et gracePeriod
        final logsSnapshot = await _firestore
            .collection('Users')
            .doc(_userEmail)
            .collection('Medications')
            .doc(medDoc.id)
            .collection('Logs')
            .get();

        for (final logDoc in logsSnapshot.docs) {
          final logData = logDoc.data();
          final logDate = _parseLogDateTime(logDoc.id);
          if (logDate == null) continue;

          // Vérifier si l'heure est dépassée de plus de 5 minutes
          // et moins de 35 minutes (pas encore traité)
          if (logDate.isAfter(gracePeriod) &&
              logDate.isBefore(cutoffTime)) {
            final isTaken = logData['isTaken'] as bool? ?? false;
            final alreadyMarked = logData['autoMarkedAsMissed'] as bool? ?? false;

            if (!isTaken && !alreadyMarked) {
              await _handleMissedDose(
                userEmail: _userEmail!,
                medName: medDoc.data()['medname'] as String? ?? 'Médicament',
                logDate: logDate,
                medDocId: medDoc.id,
                logDocId: logDoc.id,
              );
            }
          }
        }
      }
    } catch (e) {
      print('MissedMedicationService error: $e');
    }
  }

  Future<void> _handleMissedDose({
    required String userEmail,
    required String medName,
    required DateTime logDate,
    required String medDocId,
    required String logDocId,
  }) async {
    print('⚠️ Dose oubliée détectée: $medName à ${_formatTime(logDate)}');

    // 1. Marquer comme oublié dans Firestore
    try {
      await _firestore
          .collection('Users')
          .doc(userEmail)
          .collection('Medications')
          .doc(medDocId)
          .collection('Logs')
          .doc(logDocId)
          .update({
        'isTaken': false,
        'autoMarkedAsMissed': true,
        'missedAt': DateTime.now().toIso8601String(),
      });
    } catch (e) {
      print('Error marking missed: $e');
    }

    // 2. Créer un incident "Oubli de médicament"
    try {
      await _firestore.collection('Incidents').add({
        'type': 'Oubli de médicament',
        'description': 'Médicament oublié: $medName prévu à ${_formatTime(logDate)}',
        'severity': 2,
        'elderlyEmail': userEmail,
        'reporterEmail': 'system',
        'date': DateTime.now().toIso8601String(),
        'resolved': false,
        'autoGenerated': true,
      });
    } catch (e) {
      print('Error creating incident: $e');
    }

    // 3. Notifier le responsable de suivi (famille)
    try {
      final userDoc = await _firestore
          .collection('Users')
          .doc(userEmail)
          .get();
      final userData = userDoc.data();
      if (userData != null) {
        final userName = userData['name'] as String? ?? userEmail;
        final familyEmails = userData['linkedFamilyEmails'] as List<dynamic>? ?? [];
        final caretakerEmail = userData['caretakerEmail'] as String?;

        // Collecter tous les emails des responsables
        final caregiverEmails = <String>{};
        caregiverEmails.addAll(familyEmails.cast<String>());
        if (caretakerEmail != null) caregiverEmails.add(caretakerEmail);

        for (final caregiverEmail in caregiverEmails) {
          await _sendMissedMedAlert(
            caregiverEmail: caregiverEmail,
            elderlyName: userName,
            elderlyEmail: userEmail,
            medName: medName,
            scheduledTime: _formatTime(logDate),
          );
        }
      }
    } catch (e) {
      print('Error notifying caregivers: $e');
    }
  }

  Future<void> _sendMissedMedAlert({
    required String caregiverEmail,
    required String elderlyName,
    required String elderlyEmail,
    required String medName,
    required String scheduledTime,
  }) async {
    try {
      // Créer une notification Firestore pour le responsable
      await _firestore.collection('Notifications').add({
        'targetEmail': caregiverEmail,
        'title': '⚠️ Médicament oublié',
        'body': '$elderlyName n\'a pas pris "$medName" prévu à $scheduledTime.',
        'type': 'missed_medication',
        'medicationName': medName,
        'elderlyEmail': elderlyEmail,
        'elderlyName': elderlyName,
        'scheduledTime': scheduledTime,
        'sentAt': DateTime.now().toIso8601String(),
        'read': false,
      });

      // Créer un rappel pour le responsable
      await _firestore.collection('Reminders').add({
        'caregiverEmail': caregiverEmail,
        'type': 'missed_medication',
        'message': '$elderlyName n\'a pas pris "$medName" à $scheduledTime',
        'elderlyEmail': elderlyEmail,
        'createdAt': DateTime.now().toIso8601String(),
        'read': false,
      });

      print('📬 Alert sent to $caregiverEmail');
    } catch (e) {
      print('Error sending alert: $e');
    }
  }

  DateTime? _parseLogDateTime(String logId) {
    try {
      final parts = logId.split(' ');
      if (parts.length < 2) return null;
      final dateParts = parts[0].split('-');
      final timeParts = parts[1].split(':');
      if (dateParts.length < 3 || timeParts.length < 2) return null;
      return DateTime(
        int.parse(dateParts[0]),
        int.parse(dateParts[1]),
        int.parse(dateParts[2]),
        int.parse(timeParts[0]),
        int.parse(timeParts[1]),
      );
    } catch (_) {
      return null;
    }
  }

  String _formatTime(DateTime time) {
    return '${time.hour.toString().padLeft(2, '0')}:${time.minute.toString().padLeft(2, '0')}';
  }

  void dispose() => stop();
}
