class NutritionDataset {
  static List<Map<String, dynamic>> getRecipes() {
    return [
      // ===== BREAKFAST RECIPES =====
      {
        'name': 'Oatmeal with Berries & Walnuts',
        'nameFr': 'Porridge aux baies et noix',
        'nameAr': 'شوفان مع التوت والجوز',
        'type': 'breakfast',
        'ingredients': ['oats', 'blueberries', 'walnuts', 'cinnamon', 'almond milk'],
        'nutrition': [350.0, 12.0, 2.0, 0.0, 50.0, 52.0, 8.0, 8.0, 10.0],
        'brainBenefit': 'Oméga-3 et antioxydants: protègent les cellules cérébrales et améliorent la mémoire',
        'brainBenefitFr': 'Oméga-3 et antioxydants: protègent les cellules cérébrales et améliorent la mémoire',
        'brainBenefitAr': 'أوميغا 3 ومضادات الأكسدة: تحمي خلايا الدماغ وتحسن الذاكرة',
      },
      {
        'name': 'Mediterranean Shakshuka',
        'nameFr': 'Chakchouka méditerranéenne',
        'nameAr': 'شكشوكة متوسطية',
        'type': 'breakfast',
        'ingredients': ['eggs', 'tomatoes', 'bell peppers', 'onion', 'cumin', 'olive oil'],
        'nutrition': [380.0, 22.0, 5.0, 370.0, 450.0, 18.0, 4.0, 8.0, 20.0],
        'brainBenefit': 'Lycopène des tomates: réduit l\'inflammation cérébrale',
        'brainBenefitFr': 'Lycopène des tomates: réduit l\'inflammation cérébrale',
        'brainBenefitAr': 'الليكوبين في الطماطم: يقلل التهاب الدماغ',
      },
      {
        'name': 'Chia Pudding with Almonds',
        'nameFr': 'Pudding de chia aux amandes',
        'nameAr': 'بودينغ الشيا باللوز',
        'type': 'breakfast',
        'ingredients': ['chia seeds', 'almond milk', 'almonds', 'honey', 'cinnamon'],
        'nutrition': [310.0, 16.0, 2.0, 0.0, 30.0, 28.0, 12.0, 10.0, 9.0],
        'brainBenefit': 'Graines de chia riches en oméga-3 essentiels pour les neurones',
        'brainBenefitFr': 'Graines de chia riches en oméga-3 essentiels pour les neurones',
        'brainBenefitAr': 'بذور الشيا غنية بالأوميغا 3 الضرورية للخلايا العصبية',
      },
      {
        'name': 'Whole Grain Toast with Avocado & Egg',
        'nameFr': 'Pain complet à l\'avocat et œuf',
        'nameAr': 'خبز كامل مع أفوكادو وبيض',
        'type': 'breakfast',
        'ingredients': ['whole grain bread', 'avocado', 'egg', 'cherry tomatoes', 'pepper'],
        'nutrition': [370.0, 20.0, 4.0, 190.0, 380.0, 30.0, 8.0, 3.0, 15.0],
        'brainBenefit': 'Vitamine E de l\'avocat: protège les cellules cérébrales du stress oxydatif',
        'brainBenefitFr': 'Vitamine E de l\'avocat: protège les cellules cérébrales du stress oxydatif',
        'brainBenefitAr': 'فيتامين E في الأفوكادو: يحمي خلايا الدماغ من التلف التأكسدي',
      },
      {
        'name': 'Greek Yogurt with Honey & Nuts',
        'nameFr': 'Yaourt grec au miel et noix',
        'nameAr': 'زبادي يوناني بالعسل والمكسرات',
        'type': 'breakfast',
        'ingredients': ['greek yogurt', 'honey', 'walnuts', 'pumpkin seeds', 'blueberries'],
        'nutrition': [320.0, 14.0, 4.0, 15.0, 80.0, 32.0, 4.0, 20.0, 18.0],
        'brainBenefit': 'Probiotiques: soutiennent l\'axe intestin-cerveau pour la cognition',
        'brainBenefitFr': 'Probiotiques: soutiennent l\'axe intestin-cerveau pour la cognition',
        'brainBenefitAr': 'البروبيوتيك: تدعم محور الأمعاء-الدماغ للإدراك',
      },

      // ===== LUNCH RECIPES =====
      {
        'name': 'Grilled Salmon with Quinoa',
        'nameFr': 'Saumon grillé au quinoa',
        'nameAr': 'سلمون مشوي مع الكينوا',
        'type': 'lunch',
        'ingredients': ['salmon', 'quinoa', 'broccoli', 'lemon', 'olive oil'],
        'nutrition': [520.0, 24.0, 4.0, 70.0, 350.0, 38.0, 8.0, 3.0, 42.0],
        'brainBenefit': 'DHA du saumon: bloc de construction des neurones, réduit l\'inflammation',
        'brainBenefitFr': 'DHA du saumon: bloc de construction des neurones, réduit l\'inflammation',
        'brainBenefitAr': 'DHA من السلمون: لبنة بناء الخلايا العصبية، يقلل الالتهاب',
      },
      {
        'name': 'Tunisian Grilled Fish with Vegetables',
        'nameFr': 'Poisson grillé tunisien aux légumes',
        'nameAr': 'سمك مشوي تونسي مع خضروات',
        'type': 'lunch',
        'ingredients': ['sea bream', 'tomatoes', 'bell peppers', 'harissa', 'olive oil', 'lemon'],
        'nutrition': [460.0, 18.0, 3.0, 65.0, 380.0, 28.0, 6.0, 6.0, 38.0],
        'brainBenefit': 'Sélénium du poisson: protège contre le déclin cognitif lié à l\'âge',
        'brainBenefitFr': 'Sélénium du poisson: protège contre le déclin cognitif lié à l\'âge',
        'brainBenefitAr': 'السيلينيوم في السمك: يحمي من التدهور المعرفي المرتبط بالعمر',
      },
      {
        'name': 'Chicken Tagine with Prunes & Almonds',
        'nameFr': 'Tajine poulet aux pruneaux et amandes',
        'nameAr': 'طاجين دجاج بالبرقوق واللوز',
        'type': 'lunch',
        'ingredients': ['chicken', 'prunes', 'almonds', 'onion', 'turmeric', 'cinnamon', 'ginger'],
        'nutrition': [540.0, 22.0, 4.0, 95.0, 420.0, 42.0, 6.0, 14.0, 40.0],
        'brainBenefit': 'Curcumine du curcuma: traverse la barrière hémato-encéphalique, anti-inflammatoire',
        'brainBenefitFr': 'Curcumine du curcuma: traverse la barrière hémato-encéphalique, anti-inflammatoire',
        'brainBenefitAr': 'الكركمين في الكركم: يعبر حاجز الدم-الدماغ، مضاد للالتهاب',
      },
      {
        'name': 'Lentil & Vegetable Soup',
        'nameFr': 'Soupe de lentilles aux légumes',
        'nameAr': 'شوربة عدس بالخضروات',
        'type': 'lunch',
        'ingredients': ['lentils', 'carrots', 'celery', 'garlic', 'onion', 'cumin'],
        'nutrition': [380.0, 8.0, 1.0, 0.0, 350.0, 55.0, 16.0, 6.0, 22.0],
        'brainBenefit': 'Folate et fer: soutiennent le flux d\'oxygène cérébral, réduisent l\'homocystéine',
        'brainBenefitFr': 'Folate et fer: soutiennent le flux d\'oxygène cérébral, réduisent l\'homocystéine',
        'brainBenefitAr': 'حمض الفوليك والحديد: يدعمان تدفق الأكسجين الدماغي، يقللان الهوموسيستين',
      },
      {
        'name': 'Sardine Salad with Roasted Vegetables',
        'nameFr': 'Salade de sardines et légumes rôtis',
        'nameAr': 'سلطة سردين مع خضروات محمصة',
        'type': 'lunch',
        'ingredients': ['sardines', 'zucchini', 'bell peppers', 'olive oil', 'lemon', 'garlic'],
        'nutrition': [440.0, 26.0, 5.0, 110.0, 520.0, 18.0, 6.0, 5.0, 32.0],
        'brainBenefit': 'Sardines: concentré d\'oméga-3, calcium et B12 pour la myéline neuronale',
        'brainBenefitFr': 'Sardines: concentré d\'oméga-3, calcium et B12 pour la myéline neuronale',
        'brainBenefitAr': 'السردين: مصدر مركز للأوميغا 3 والكالسيوم وB12 لغلاف الميالين',
      },
      {
        'name': 'Spinach & Feta Stuffed Peppers',
        'nameFr': 'Poivrons farcis aux épinards et feta',
        'nameAr': 'فلفل محشي بالسبانخ والفيتا',
        'type': 'lunch',
        'ingredients': ['bell peppers', 'spinach', 'feta cheese', 'brown rice', 'herbs'],
        'nutrition': [400.0, 16.0, 7.0, 30.0, 550.0, 44.0, 8.0, 6.0, 18.0],
        'brainBenefit': 'Légumes verts: ralentissent le déclin cognitif de 40% (étude Rush)',
        'brainBenefitFr': 'Légumes verts: ralentissent le déclin cognitif de 40% (étude Rush)',
        'brainBenefitAr': 'الخضروات الورقية: تبطئ التدهور المعرفي بنسبة 40% (دراسة راش)',
      },

      // ===== DINNER RECIPES =====
      {
        'name': 'Baked White Fish with Lemon & Herbs',
        'nameFr': 'Poisson blanc au four citron et herbes',
        'nameAr': 'سمك أبيض مشوي بالليمون والأعشاب',
        'type': 'dinner',
        'ingredients': ['white fish', 'lemon', 'dill', 'potatoes', 'olive oil', 'garlic'],
        'nutrition': [420.0, 14.0, 2.0, 60.0, 280.0, 35.0, 5.0, 3.0, 36.0],
        'brainBenefit': 'Vitamine B12: essentielle pour la gaine de myéline et la fonction nerveuse',
        'brainBenefitFr': 'Vitamine B12: essentielle pour la gaine de myéline et la fonction nerveuse',
        'brainBenefitAr': 'فيتامين B12: ضروري لغلاف الميالين ووظيفة الأعصاب',
      },
      {
        'name': 'Tunisian Vegetable Couscous',
        'nameFr': 'Couscous aux légumes tunisien',
        'nameAr': 'كسكسي بالخضار التونسي',
        'type': 'dinner',
        'ingredients': ['couscous', 'carrots', 'turnips', 'chickpeas', 'raisins', 'spices'],
        'nutrition': [450.0, 10.0, 1.0, 0.0, 250.0, 72.0, 10.0, 12.0, 14.0],
        'brainBenefit': 'Vitamines B des céréales: synthèse des neurotransmetteurs (sérotonine, dopamine)',
        'brainBenefitFr': 'Vitamines B des céréales: synthèse des neurotransmetteurs (sérotonine, dopamine)',
        'brainBenefitAr': 'فيتامينات B في الحبوب: تخليق الناقلات العصبية (سيروتونين، دوبامين)',
      },
      {
        'name': 'Turmeric Chicken Stew with Sweet Potato',
        'nameFr': 'Ragoût poulet curcuma et patate douce',
        'nameAr': 'يخنة دجاج بالكركم والبطاطا الحلوة',
        'type': 'dinner',
        'ingredients': ['chicken', 'sweet potato', 'turmeric', 'spinach', 'onion', 'garlic', 'coconut milk'],
        'nutrition': [480.0, 18.0, 8.0, 75.0, 380.0, 40.0, 7.0, 8.0, 34.0],
        'brainBenefit': 'Curcumine + bêta-carotène: synergie anti-inflammatoire cérébrale puissante',
        'brainBenefitFr': 'Curcumine + bêta-carotène: synergie anti-inflammatoire cérébrale puissante',
        'brainBenefitAr': 'كركمين + بيتا كاروتين: تآزر قوي مضاد لالتهاب الدماغ',
      },
      {
        'name': 'Stuffed Eggplant with Chickpeas',
        'nameFr': 'Aubergines farcies aux pois chiches',
        'nameAr': 'باذنجان محشي بالحمص',
        'type': 'dinner',
        'ingredients': ['eggplant', 'chickpeas', 'tomatoes', 'onion', 'garlic', 'olive oil', 'cumin'],
        'nutrition': [350.0, 14.0, 2.0, 0.0, 320.0, 42.0, 12.0, 10.0, 12.0],
        'brainBenefit': 'Pois chiches: glucose stable pour énergie cérébrale prolongée sans pic glycémique',
        'brainBenefitFr': 'Pois chiches: glucose stable pour énergie cérébrale prolongée sans pic glycémique',
        'brainBenefitAr': 'الحمص: جلوكوز مستقر لطاقة دماغية ممتدة بدون ارتفاع السكر',
      },
      {
        'name': 'Moroccan Harira Soup',
        'nameFr': 'Harira marocaine',
        'nameAr': 'حريرة مغربية',
        'type': 'dinner',
        'ingredients': ['tomatoes', 'lentils', 'chickpeas', 'celery', 'onion', 'ginger', 'cinnamon'],
        'nutrition': [370.0, 8.0, 1.0, 0.0, 480.0, 54.0, 12.0, 8.0, 16.0],
        'brainBenefit': 'Gingembre: améliore la circulation sanguine cérébrale et la concentration',
        'brainBenefitFr': 'Gingembre: améliore la circulation sanguine cérébrale et la concentration',
        'brainBenefitAr': 'الزنجبيل: يحسن الدورة الدموية الدماغية والتركيز',
      },

      // ===== SNACKS =====
      {
        'name': 'Walnuts & Dark Chocolate (85%)',
        'nameFr': 'Noix et chocolat noir 85%',
        'nameAr': 'جوز وشوكولاتة داكنة 85%',
        'type': 'snack',
        'ingredients': ['walnuts', 'dark chocolate', 'dried blueberries'],
        'nutrition': [190.0, 16.0, 5.0, 0.0, 5.0, 14.0, 4.0, 6.0, 5.0],
        'brainBenefit': 'Flavonoïdes du chocolat: augmentent le flux sanguin cérébral de 20%',
        'brainBenefitFr': 'Flavonoïdes du chocolat: augmentent le flux sanguin cérébral de 20%',
        'brainBenefitAr': 'فلافونويدات الشوكولاتة: تزيد تدفق الدم الدماغي بنسبة 20%',
      },
      {
        'name': 'Dates Stuffed with Almonds',
        'nameFr': 'Dattes farcies aux amandes',
        'nameAr': 'تمر محشي باللوز',
        'type': 'snack',
        'ingredients': ['dates', 'almonds', 'cinnamon'],
        'nutrition': [170.0, 8.0, 1.0, 0.0, 2.0, 28.0, 4.0, 22.0, 3.0],
        'brainBenefit': 'Dattes: énergie rapide avec fibres pour éviter les pics glycémiques',
        'brainBenefitFr': 'Dattes: énergie rapide avec fibres pour éviter les pics glycémiques',
        'brainBenefitAr': 'التمر: طاقة سريعة مع ألياف لتجنب ارتفاع السكر',
      },
      {
        'name': 'Berry Smoothie Bowl',
        'nameFr': 'Bol smoothie aux baies',
        'nameAr': 'وعاء سموذي بالتوت',
        'type': 'snack',
        'ingredients': ['mixed berries', 'banana', 'almond milk', 'flax seeds'],
        'nutrition': [200.0, 6.0, 1.0, 0.0, 40.0, 34.0, 8.0, 16.0, 5.0],
        'brainBenefit': 'Anthocyanines des baies: améliorent la mémoire et ralentissent le vieillissement cérébral',
        'brainBenefitFr': 'Anthocyanines des baies: améliorent la mémoire et ralentissent le vieillissement cérébral',
        'brainBenefitAr': 'أنثوسيانين التوت: يحسن الذاكرة ويبطئ شيخوخة الدماغ',
      },
      {
        'name': 'Cucumber & Hummus',
        'nameFr': 'Concombre et houmous',
        'nameAr': 'خيار وحمص',
        'type': 'snack',
        'ingredients': ['cucumber', 'hummus', 'paprika'],
        'nutrition': [140.0, 8.0, 1.0, 0.0, 200.0, 14.0, 4.0, 3.0, 5.0],
        'brainBenefit': 'Hydratation: critique pour le fonctionnement optimal du cerveau (le cerveau est 75% eau)',
        'brainBenefitFr': 'Hydratation: critique pour le fonctionnement optimal du cerveau (le cerveau est 75% eau)',
        'brainBenefitAr': 'الترطيب: ضروري لعمل الدماغ الأمثل (الدماغ 75% ماء)',
      },
      {
        'name': 'Apple with Almond Butter',
        'nameFr': 'Pomme au beurre d\'amande',
        'nameAr': 'تفاح بزبدة اللوز',
        'type': 'snack',
        'ingredients': ['apple', 'almond butter', 'cinnamon'],
        'nutrition': [220.0, 14.0, 1.0, 0.0, 5.0, 22.0, 6.0, 14.0, 7.0],
        'brainBenefit': 'Quercétine de la pomme: protège les neurones du stress oxydatif',
        'brainBenefitFr': 'Quercétine de la pomme: protège les neurones du stress oxydatif',
        'brainBenefitAr': 'كيرسيتين التفاح: يحمي الخلايا العصبية من الإجهاد التأكسدي',
      },
    ];
  }
}
